on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload
        uses: withastro/action@v2
        with:
          package-manager: bun@latest
